### ISSUE TITLE
收费注册哪里好像不行了，一直返回4 注册码错误

### ISSUE THREAD

**Issue by YunMengs** [astrid9527/RegisterDmSoftConsoleApp#1]

**Comment by astrid9527** [comment]
源码是没有提供注册码的，[public const string DmRegCode = "";](https://github.com/astrid9527/RegisterDmSoftConsoleApp/blob/e2b013f36e8b7652109e45fd85082e4b6ea8aeca/Configs/DmConfig.cs#L21)。

请自行获取注册码
